timetracking/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",views.index,name="index" ),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path("project/",include("project.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from . import views
from django.urls import path,include
from .views import ManagerRegisterView,DeveloperRegisterView,UserLoginView,UserDetailView
from django.contrib.auth.views import LogoutView


urlpatterns = [

#localhost:8000/user/manager_register/
path("manager_register/",ManagerRegisterView.as_view(),name="manager_register"),
path("developer_register/",DeveloperRegisterView.as_view(),name="developer_register"),
path("login/",UserLoginView.as_view(),name="login"),
# path("logout/",LogoutView.as_view(),name="logout"),
path('gym/', views.gym),
path('logout/', LogoutView.as_view(next_page='login'), name='logout'), # add (next_page='login') Redirect to the login page when click on logout button
 
path("manager_dashboard/",views.ManagerDashboardView.as_view(),name="manager_dashboard"),
path("developer_dashboard/",views.DeveloperDashboardView.as_view(),name="developer_dashboard"),
# path("manager_dashboard/",views.DeveloperDashboardView.as_view(),name="manager_dashboard"),
# path("userdetail/?id",UserDetailView.as_view(),name="user_detail"), 
path("userdetail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),

]

project/models.py
from django.db import models
from user.models import User


# Create your models here.
techChoices = (
    ("Django", "Django"),
    ("Flask", "Flask"),
    ("Python", "Python"),
    ("Java", "Java"),
    ("C++", "C++"),
    ("C#", "C#"),
)

# models.py

from django.db import models




class Project(models.Model):
    title = models.CharField(max_length=100, null=False)
    description = models.TextField(null=False)
    technology = models.CharField(max_length=100, choices=techChoices, null=False)
    estimated_hours = models.PositiveIntegerField(null=False)
    startDate = models.DateField(null=False)
    endDate = models.DateField(null=False)
    
    class Meta:
        db_table = "project"
    
    def __str__(self):
        return self.title 

class ProjectTeam(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='teams')  # Adjusted related_name
    
    class Meta:
        db_table = "projectteam"
    
    def __str__(self):
        return f'Team for {self.project.title}'
    
    
from .models import ProjectTeam

def project_detail(request, project_id):
    project_teams = ProjectTeam.objects.filter(project_id=project_id)


# class Status(models.Model):
#     status = models.IntegerField(primary_key=True)
#     status_Name = models.CharField(unique=True, max_length=100, null=False, default='default_status_name')
    
#     class Meta:
#         db_table = "status"



# models.py
statusChoices = [
    ('New', 'New'),
    ('Open', 'Open'),
    ('In Progress', 'In Progress'),
    ('Completed', 'Completed'),
    ('On Hold', 'On Hold'),
    ('Canceled', 'Canceled'),
    ('Active', 'Active'),
    ('Priority', 'Priority'),
]

# forms.py
from .models import statusChoices



class ProjectModule(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    module_Name = models.CharField(unique=True, max_length=100)
    description = models.TextField(null=False)
    estimated_Minutes = models.PositiveIntegerField(null=False)
    status = models.CharField(max_length=100, choices=statusChoices,null=False)
    # technology = models.CharField(max_length=100, choices=techChoices, null=False)
    # status = models.ForeignKey(Status, choices=statusChoices, on_delete=models.CASCADE)
    start_Date = models.DateField(null=False)
    total_Util_Minutes = models.PositiveIntegerField(null=False)
    
    class Meta:
        db_table = "project_module"
    
    def __str__(self):
        return self.module_Name 

taskpriority = [
    ('Low', 'Low'),
    ('Medium', 'Medium'),
    ('High', 'High'),
    ('Critical', 'Critical'),
]

taskstatus = [
    ('To do', 'To do'),
    # ('Open', 'Open'),
    ('In progress', 'In progress'),
    ('Done', 'Done'),
    # ('On Hold', 'On Hold'),  # Add 'On Hold' to the choices
    # ('Canceled', 'Canceled'),
    # ('Active', 'Active'),
    # ('Priority', 'Priority'),
]

        
class Task(models.Model):
    module = models.ForeignKey(ProjectModule, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True)
    taskstatus = models.CharField(max_length=100, choices=taskstatus, null=True)
    
    description = models.TextField(null=True)
    priority = models.CharField(max_length=100, choices= taskpriority, null = True)
    estimated_Minutes = models.PositiveIntegerField(null=True)
    total_util_minutes = models.PositiveIntegerField(null= True)
    
    # created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # Add created_by field
    
    
    class Meta:
        db_table = "task"
    def __str__(self):
        return self.title
        
class Badge(models.Model):
    badge = models.CharField(unique=True, max_length=100, default='default_value_here')
    
    class Meta:
        db_table = "badge"

        
class UserTask(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    # total_util_minutes = models.PositiveIntegerField(null=True)
    created_at = models.DateField(auto_now_add=True, null= True)
    updated_at = models.DateField(auto_now=True)
    
    class Meta:
        db_table = "user_task"
    
    def __str__(self):
        return self.task.title+' - '+self.user.username

class TaskBadge(models.Model):

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE)
    
    class Meta:
        db_table = "task_badge"

project/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy , reverse
from .forms import ProjectCreationForm, ProjectTeamCreationForm, TaskAsignmentForm,TaskCreationForm
from .models import Project, ProjectTeam,UserTask , Task
from user.models import User 
from django.shortcuts import render

class ProjectCreationView(CreateView):
    template_name = 'project/create.html'
    model = Project
    form_class = ProjectCreationForm
    success_url = reverse_lazy('project_list')

class ProjectListView(ListView):
    template_name = 'project/list.html'
    model = Project
    context_object_name = 'projects'
    
from django.shortcuts import render
from .models import Project

def project_list(request):
    projects = Project.objects.all()
    return render(request, 'project/list.html', {'projects': projects})


class ProjectUserListView(ListView):
    template_name = 'project/userlist.html'
    model = User
    context_object_name = 'users'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.all()
        return context

# views.py

# views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import ProjectTeamCreationForm
from .models import Project, ProjectTeam

# class ProjectTeamCreateView(CreateView):
#     template_name = 'project/create_team.html'  # Create a template for team creation
#     form_class = ProjectTeamCreationForm

#     def get_initial(self):
#         initial = super().get_initial()
#         project_id = self.kwargs.get('project_id')
#         project = get_object_or_404(Project, pk=project_id)
#         initial['project'] = project
#         return initial

#     def get_success_url(self):
#         project_id = self.kwargs.get('project_id')
#         return reverse_lazy('project_detail', kwargs={'project_id': project_id})

from django import forms
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .models import Project, ProjectTeam
from .forms import ProjectTeamCreationForm

class ProjectTeamCreateView(CreateView):
    template_name = 'project/create_team.html'
    form_class = ProjectTeamCreationForm

    def get_initial(self):
        initial = super().get_initial()
        project_id = self.kwargs.get('project_id')
        project = get_object_or_404(Project, pk=project_id)
        initial['project'] = project
        return initial

    def get_success_url(self):
        project_id = self.kwargs.get('project_id')
        return reverse_lazy('project_detail', kwargs={'project_id': project_id})
    

def get_form(self, form_class=None):
    project_id = self.kwargs.get('project_id')
    project = get_object_or_404(Project, pk=project_id)
    selected_users = project.projectteam_set.values_list('users', flat=True).distinct()
    form_kwargs = self.get_form_kwargs()
    form_kwargs['project_id'] = project_id
    form_kwargs['selected_users'] = selected_users
    return ProjectTeamCreationForm(**form_kwargs)


    def form_valid(self, form):
        # Handle the deletion of selected users from the form data
        project_id = self.kwargs.get('project_id')
        project = get_object_or_404(Project, pk=project_id)
        selected_users = form.cleaned_data['users']
        existing_users = project.projectteam_set.values_list('users', flat=True)
        users_to_delete = set(existing_users).intersection(selected_users)
        project.projectteam_set.filter(users__in=users_to_delete).delete()
        return super().form_valid(form)






    # def get_initial(self):
    #     initial = super().get_initial()
    #     user_id = self.kwargs.get('user_id')
    #     users = get_object_or_404(User, pk=user_id)
    #     initial['user'] = users
    #     return initial


    # def get_queryset(self):
    #     # Get the logged-in user
    #     user = self.request.user
    #     # Filter expenses based on the logged-in user
    #     queryset = super().get_queryset().filter(user=user)
    #     return queryset

class ProjectDetailView(DetailView):
    template_name = 'project/detail.html'
    model = Project
    context_object_name = 'project'
    
    # views.py

from django.shortcuts import render
from .models import Project, ProjectTeam

# views.py
from django.shortcuts import render, get_object_or_404
from .models import Project, ProjectTeam

def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    team_members = ProjectTeam.objects.filter(project_id=project_id)
    context = {
        'project': project,
        'team_members': team_members,
    }
    return render(request, 'project/detail.html', context)

# views.py
from django.shortcuts import redirect

def delete_user_from_team(request, project_id, user_id):
    project = get_object_or_404(Project, pk=project_id)
    user = get_object_or_404(User, pk=user_id)
    team_member = ProjectTeam.objects.filter(project=project, users=user)
    team_member.delete()
    return redirect('project_detail', project_id=project_id)


# Updated view
def update_project(request, project_id):
    project = Project.objects.get(id=project_id)
    team_members = project.projectteam_set.all()  # Assuming you have a related_name set for the ForeignKey in the ProjectTeam model
    context = {
        'project': project,
        'team_members': team_members,
    }
    return render(request, 'update_project.html', context)

    


# from django.shortcuts import render
# from .models import Project, ProjectTeam

# def project_detail(request, project_id):
#     project = Project.objects.get(id=project_id)
#     project_team = ProjectTeam.objects.filter(project=project).select_related('user')
    
#     # Create a set to store unique user IDs
#     unique_users = set()
    
#     # Create a list to store unique team members
#     unique_team_members = []
    
#     # Create a set to store unique user names
#     unique_usernames = set(team_member.user.username for team_member in project_team)
    
#     # Iterate over project_team and filter out duplicate users
#     for team_member in project_team:
#         if team_member.user.id not in unique_users:
#             unique_users.add(team_member.user.id)
#             unique_team_members.append(team_member.user)
    
#     context = {
#         'project': project,
#         'project_team': unique_team_members,
#     }
#     return render(request, 'project/detail.html', context)





class ProjectUpdateView(UpdateView):
    template_name = 'project/update.html'
    model = Project
    form_class = ProjectCreationForm
    success_url = reverse_lazy('project_list')



class ProjectDeleteView(DeleteView):
    template_name = 'project/delete.html'
    model = Project
    success_url = reverse_lazy('project_list')

class UserListView(ListView):
    template_name = 'project/userlist.html'
    model = User
    context_object_name = 'users'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.all()
        return context


from django.db import models

class User(models.Model):
    username = models.CharField(max_length=150, unique=True)  # Ensure unique usernames
    email = models.EmailField(max_length=255, unique=True)
    # Add other fields as needed
    
    def __str__(self):
        return self.username









from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy
from .forms import ProjectModuleCreationForm
from .models import Project, ProjectModule

# View for creating a new project module
# views.py

# views.py

# views.py

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .models import ProjectModule
from .forms import ProjectModuleCreationForm
from project.models import Project  # Assuming project module is imported

class ProjectModuleCreateView(CreateView):
    template_name = 'project/module_create.html'
    form_class = ProjectModuleCreationForm
    success_url = reverse_lazy('module_list')

    def get_initial(self):
        initial = super().get_initial()
        project_id = self.kwargs.get('project_id')
        project = get_object_or_404(Project, pk=project_id)
        initial['project'] = project
        return initial

    # def get_success_url(self):
    #     project_id = self.kwargs.get('project_id')
    #     return reverse_lazy('project_detail', kwargs={'project_id': project_id})



# View for updating an existing project module
class ProjectModuleUpdateView(UpdateView):
    template_name = 'project/module_update.html'
    model = ProjectModule
    form_class = ProjectModuleCreationForm
    success_url = reverse_lazy('module_list')

# View for deleting an existing project module
class ProjectModuleDeleteView(DeleteView):
    template_name = 'project/module_delete.html'
    model = ProjectModule
    success_url = reverse_lazy('module_list')

# View for listing all project modules
from django.shortcuts import render
from django.views.generic import ListView
from .models import ProjectModule

class ProjectModuleListView(ListView):
    template_name = 'project/module_list.html'
    model = ProjectModule
    context_object_name = 'project_modules'

    def get_queryset(self):
        # Customize queryset based on your requirements
        # For example, filter by project or any other condition
        return ProjectModule.objects.all()  # Retrieve all project modules
    
class CreateTaskView(CreateView):
    model = Task
    template_name = 'project/create_task.html'
    form_class = TaskCreationForm

templates/index.html
<h3> Index </h3>

templates/sidebar.html
<style>
  .bg-glass {
    background-color: hsla(0, 0%, 10%, 0.8) !important;
    backdrop-filter: saturate(2000%) blur(60px);
    
    
    border-radius: 22px;
    
  }

  {% comment %} .bg-glass1 {
    background-color: rgba(0, 0%, 10%, 0.8) !important; /* Transparent white background */
    backdrop-filter: saturate(2000%) blur(60px); /* Adjust blur intensity for glass effect */
    border-radius: 12px;
} {% endcomment %}


  
  </style>
<aside
  class="sidenav  card bg-glass bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 ps"
  id="sidenav-main"
>
  <div class="sidenav-header">
    {% comment %} <i
      class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
      aria-hidden="true"
      id="iconSidenav"
    ></i> {% endcomment %}
    <a
      class="navbar-brand m-4"
      href="{% url 'developer_dashboard' %}"
      target="_blank">
       {% comment %} <img 
        src="./assets/img/logo-ct-dark.png"
        class="navbar-brand-img h-100"
        alt="main_logo"
      /> {% endcomment %}
      <span class="ms-4 font-weight-bold">Time Tracking</span> 
    </a>
  </div>
  {% comment %} <hr class="horizontal dark mt-0" /> {% endcomment %}
  {% comment %} <h6>*********************</h6>  {% endcomment %}



  {% if user.is_manager == True  %}
  {% comment %} <a class="nav-link"> {% endcomment %}
  <div
    class=" w-auto ps ps--active-y mt-1"
    id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          {% comment %} <li class="nav-item {% if request.path == '/project/create/' %}active{% endif %}"> {% endcomment %}
        <a class="nav-link  b {% if request.path == '/user/manager_dashboard/' %} bg-glass{% endif %}" href="{% url 'manager_dashboard' %}">
          {% comment %} <a class="nav-link " href="{% url 'project_create' %}"> {% endcomment %}
            <div
              class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
            >
              <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>


        <li class="nav-item ">

          <a class="nav-link {% if request.path == '/project/list/' %}bg-glass{% endif %}"  href= "{% url 'project_list' %}"  >
            <div
              class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
            >
              <i
                class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"
              ></i>
            </div>
            <span class="nav-link-text ms-1">Project List</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link  b {% if request.path == '/project/create/' %} bg-glass{% endif %}" href="{% url 'project_create' %}">
            <div
              class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
            >
              <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Create Project</span>
          </a>
        </li>

        
          <a class="nav-link  b {% if request.path == '/project/modulelist/' %} bg-glass{% endif %}" href="{% url 'module_list' %}"> 
            {% comment %} <a class="nav-link b {% if request.path == 'project/<int:project_id>/create-team/' %} bg-glass{% endif %}" href="{% url 'project_team_create' %}">  {% endcomment %}

            <div
              class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
            >
              <i class="ni ni-app text-info text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Module List</span>
          </a>
        </li>


        <li class="nav-item">
          <a class="nav-link b {% if request.path == '/project/userlist/' %} bg-glass{% endif %}" href="{% url 'user_list' %}">
            <div
              class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
            >
              <i class="ni ni-world-2 text-danger text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">User List</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link b {% if request.path == '/project/task_list/' %} bg-glass{% endif %}" href="{% url 'task_list' %}">
            <div
              class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
            >
              <i class="ni ni-settings text-danger text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Task List</span>
          </a>
        </li>
        


        {% comment %} <li class="nav-item">
          <a href="javascript:;" class="nav-link text-white font-weight-bold px-6">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-person me-1" viewBox="0 0 20 20">
              <path d="M10 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm0 1a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm5-5a7 7 0 1 1-14 0 7 7 0 0 1 14 0z"/>
            </svg>
            {% if request.user.is_authenticated %}
              {{ request.user }}
            {% endif %}
          </a>
        </li> {% endcomment %}
        


          {% comment %} <a class="nav-link" href="./pages/profile.html">
            <div
              class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
            >
              <i class="ni ni-single-02 text-dark text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Profile</span>
          </a> 
          
        </li>{% endcomment %}


        {% comment %} <li class="nav-item">
          <a class="nav-link" href="./pages/sign-in.html">
            <div
              class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
            >
              <i class="ni ni-single-copy-04 text-warning text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Sign In</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="./pages/sign-up.html">
            <div
              class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
            >
              <i class="ni ni-collection text-info text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Sign Up</span>
          </a>
        </li> {% endcomment %}
      </ul>

    
    
  </div>
  {% else %}
   
  
    <div
      class="collapse navbar-collapse w-auto ps ps--active-y"
      id="sidenav-collapse-main">
        <ul class="navbar-nav">
          <li class="nav-item">
            {% comment %} <li class="nav-item {% if request.path == '/project/create/' %}active{% endif %}"> {% endcomment %}
          <a class="nav-link  b {% if request.path == '/user/developer_dashboard/' %} bg-glass{% endif %}" href="{% url 'developer_dashboard' %}">
            {% comment %} <a class="nav-link " href="{% url 'project_create' %}"> {% endcomment %}
              <div
                class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
              >
                <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">Dashboard</span>
            </a>
          </li>


          <li class="nav-item ">

            <a class="nav-link {% if request.path == '/project/list/' %}bg-glass{% endif %}"  href= "{% url 'project_list' %}"  >
              <div
                class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
              >
                <i
                  class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"
                ></i>
              </div>
              <span class="nav-link-text ms-1">Project List</span>
            </a>
          </li>

          

          
            <a class="nav-link  b {% if request.path == '/project/modulelist/' %} bg-glass{% endif %}" href="{% url 'module_list' %}"> 
              {% comment %} <a class="nav-link b {% if request.path == 'project/<int:project_id>/create-team/' %} bg-glass{% endif %}" href="{% url 'project_team_create' %}">  {% endcomment %}

              <div
                class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
              >
                <i class="ni ni-app text-info text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">Module List</span>
            </a>
          </li>


          <li class="nav-item">
            <a class="nav-link b {% if request.path == '/project/userlist/' %} bg-glass{% endif %}" href="{% url 'user_list' %}">
              <div
                class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
              >
                <i class="ni ni-world-2 text-danger text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">User List</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link b {% if request.path == '/project/task_list/' %} bg-glass{% endif %}" href="{% url 'task_list' %}">
              <div
                class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center"
              >
                <i class="ni ni-settings text-danger text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">Task List</span>
            </a>
          </li>
          

        
        </ul>

      
      
    </div>
  
  {% endif %}
  {% comment %} <div class="sidenav-footer mx-3">
    <div class="card card-plain shadow-none" id="sidenavCard">
      <img
        class="w-50 mx-auto"
        src="./assets/img/illustrations/icon-documentation.svg"
        alt="sidebar_illustration"
      />
      <div class="card-body text-center p-3 w-100 pt-0">
        <div class="docs-info">
          <h6 class="mb-0">Need help?</h6>
          <p class="text-xs font-weight-bold mb-0">Please check our docs</p>
        </div>
      </div>
    </div> {% endcomment %}
    {% comment %} <a
      href="https://www.creative-tim.com/learning-lab/bootstrap/license/argon-dashboard"
      target="_blank"
      class="btn btn-dark btn-sm w-100 mb-3"
      >Documentation</a
    > {% endcomment %}
    {% comment %} <a
      class="btn btn-primary btn-sm mb-0 w-100"
      href="{% url 'logout' %}"
      
      type="button"
      >Logout
      </a> {% endcomment %}
      
      {% comment %} <h6>*********************</h6> {% endcomment %}





      {% comment %} <li class="nav-item mt-3"> {% endcomment %}
        <h6
          class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6"
        >
          Account pages
        </h6>
      </li>
      <a class="card-body text-center p-3 w-100 pt-0">

        <form action="{% url 'logout' %}" method="post" >
          {% csrf_token %}
          <button type="submit" class="btn btn-dark btn-sm btn btn-outline-gray btn-sm mb-0 w-100">LOGOUT</button>
       </form>
       
      </a>
  </div>
  <div class="ps__rail-x" style="left: 0px; bottom: 0px">
    <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px"></div>
  </div>
  <div class="ps__rail-y" style="top: 0px; right: 0px">
    <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px"></div>
  </div>
</aside>