project/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from .views import (ProjectCreationView, ProjectListView, ProjectTeamCreateView, ProjectDetailView, ProjectModuleCreateView,ProjectModuleUpdateView,ProjectModuleDeleteView, UpdateStatusView,
                    ProjectDeleteView, ProjectUpdateView, UserListView, ProjectModuleListView,AsignTaskView,CreateTaskView , ProjectTaskListView,ProjectTaskDeleteView,ProjectTaskUpdateView, UserDeleteView)

urlpatterns = [
 
 path("create/",ProjectCreationView.as_view(),name="project_create"),
 path("list/",ProjectListView.as_view(),name="project_list"),
 path("userlist/",UserListView.as_view(),name="user_list"),
  path('<int:project_id>/delete_user_from_team/<int:user_id>/', views.delete_user_from_team, name='delete_user_from_team'),

# path("create_team/",ProjectTeamCreateView.as_view(),name="project_team_create"),
  
# project TEAM
#  path("detail/<int:pk>/",ProjectDetailView.as_view(),name="project_detail"), 
 path('<int:project_id>/create-team/', ProjectTeamCreateView.as_view(), name='project_team_create'),
 path('detail/<int:project_id>/', views.project_detail, name='project_detail'),
 path("update/<int:pk>/",ProjectUpdateView.as_view(),name="project_update"),
 path("delete/<int:pk>/",ProjectDeleteView.as_view(),name="project_delete"),
 
 path("<int:pk>/userdelete/", UserDeleteView.as_view(), name="userdelete"),  # URL for deleting user 
 

# project module 
# path("project/modulecreate/", ProjectModuleCreateView.as_view(), name="module_create"),  # URL for creating project module
    path("<int:project_id>/modulecreate/", ProjectModuleCreateView.as_view(), name="module_create"),
    path("<int:pk>/moduleupdate/", ProjectModuleUpdateView.as_view(), name="module_update"),  # URL for updating project module
    path("<int:pk>/moduledelete/", ProjectModuleDeleteView.as_view(), name="module_delete"),  # URL for deleting project module
    path("modulelist/", ProjectModuleListView.as_view(), name="module_list"),  # URL for listing project modules
   #  path('project/<int:project_id>/update-team/', views.project_team_update, name='project_team_update'),

# project TASK
path("<int:user_id>/task_assign/", AsignTaskView.as_view(), name="task_assign"),
path("task_list/", ProjectTaskListView.as_view(), name="task_list"),  # URL for listing project modules
path("<int:project_id>/create_task/",CreateTaskView.as_view(), name="create_task"),
path("<int:pk>/taskupdate/", ProjectTaskUpdateView.as_view(), name="task_update"),  # URL for updating project task
path("<int:pk>/taskdelete/", ProjectTaskDeleteView.as_view(), name="task_delete"),  # URL for deleting project task
path('<int:pk>/updatestatus/', UpdateStatusView.as_view(), name='update_status'),
    

#  path("<int:project_id>/task_assign/",AsignTaskView.as_view(), name="task_assign"),
 
]

timetracking/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",views.index,name="index" ),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path("project/",include("project.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from . import views
from django.urls import path,include
from .views import ManagerRegisterView,DeveloperRegisterView,UserLoginView,UserDetailView
from django.contrib.auth.views import LogoutView


urlpatterns = [

#localhost:8000/user/manager_register/
path("manager_register/",ManagerRegisterView.as_view(),name="manager_register"),
path("developer_register/",DeveloperRegisterView.as_view(),name="developer_register"),
path("login/",UserLoginView.as_view(),name="login"),
# path("logout/",LogoutView.as_view(),name="logout"),
path('gym/', views.gym),
path('logout/', LogoutView.as_view(next_page='login'), name='logout'), # add (next_page='login') Redirect to the login page when click on logout button
 
path("manager_dashboard/",views.ManagerDashboardView.as_view(),name="manager_dashboard"),
path("developer_dashboard/",views.DeveloperDashboardView.as_view(),name="developer_dashboard"),
# path("manager_dashboard/",views.DeveloperDashboardView.as_view(),name="manager_dashboard"),
# path("userdetail/?id",UserDetailView.as_view(),name="user_detail"), 
path("userdetail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),

]

project/models.py
from django.db import models
from user.models import User


# Create your models here.
techChoices = (
    ("Django", "Django"),
    ("Flask", "Flask"),
    ("Python", "Python"),
    ("Java", "Java"),
    ("C++", "C++"),
    ("C#", "C#"),
)

# models.py

from django.db import models




class Project(models.Model):
    title = models.CharField(max_length=100, null=False)
    description = models.TextField(null=False)
    technology = models.CharField(max_length=100, choices=techChoices, null=False)
    estimated_hours = models.PositiveIntegerField(null=False)
    startDate = models.DateField(null=False)
    endDate = models.DateField(null=False)
    
    class Meta:
        db_table = "project"
    
    def __str__(self):
        return self.title 

class ProjectTeam(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='teams')  # Adjusted related_name
    
    class Meta:
        db_table = "projectteam"
    
    def __str__(self):
        return f'Team for {self.project.title}'
    
    
from .models import ProjectTeam

def project_detail(request, project_id):
    project_teams = ProjectTeam.objects.filter(project_id=project_id)


# class Status(models.Model):
#     status = models.IntegerField(primary_key=True)
#     status_Name = models.CharField(unique=True, max_length=100, null=False, default='default_status_name')
    
#     class Meta:
#         db_table = "status"



# models.py
statusChoices = [
    ('New', 'New'),
    ('Open', 'Open'),
    ('In Progress', 'In Progress'),
    ('Completed', 'Completed'),
    ('On Hold', 'On Hold'),
    ('Canceled', 'Canceled'),
    ('Active', 'Active'),
    ('Priority', 'Priority'),
]

# forms.py
from .models import statusChoices



class ProjectModule(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    module_Name = models.CharField(unique=True, max_length=100)
    description = models.TextField(null=False)
    estimated_Minutes = models.PositiveIntegerField(null=False)
    status = models.CharField(max_length=100, choices=statusChoices,null=False)
    # technology = models.CharField(max_length=100, choices=techChoices, null=False)
    # status = models.ForeignKey(Status, choices=statusChoices, on_delete=models.CASCADE)
    start_Date = models.DateField(null=False)
    total_Util_Minutes = models.PositiveIntegerField(null=False)
    
    class Meta:
        db_table = "project_module"
    
    def __str__(self):
        return self.module_Name 

taskpriority = [
    ('Low', 'Low'),
    ('Medium', 'Medium'),
    ('High', 'High'),
    ('Critical', 'Critical'),
]

taskstatus = [
    ('To do', 'To do'),
    # ('Open', 'Open'),
    ('In progress', 'In progress'),
    ('Done', 'Done'),
    # ('On Hold', 'On Hold'),  # Add 'On Hold' to the choices
    # ('Canceled', 'Canceled'),
    # ('Active', 'Active'),
    # ('Priority', 'Priority'),
]

        
class Task(models.Model):
    module = models.ForeignKey(ProjectModule, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True)
    taskstatus = models.CharField(max_length=100, choices=taskstatus, null=True)
    
    description = models.TextField(null=True)
    priority = models.CharField(max_length=100, choices= taskpriority, null = True)
    estimated_Minutes = models.PositiveIntegerField(null=True)
    total_util_minutes = models.PositiveIntegerField(null= True)
    
    # created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # Add created_by field
    
    
    class Meta:
        db_table = "task"
    def __str__(self):
        return self.title
        
class Badge(models.Model):
    badge = models.CharField(unique=True, max_length=100, default='default_value_here')
    
    class Meta:
        db_table = "badge"

        
class UserTask(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    # total_util_minutes = models.PositiveIntegerField(null=True)
    created_at = models.DateField(auto_now_add=True, null= True)
    updated_at = models.DateField(auto_now=True)
    
    class Meta:
        db_table = "user_task"
    
    def __str__(self):
        return self.task.title+' - '+self.user.username

class TaskBadge(models.Model):

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE)
    
    class Meta:
        db_table = "task_badge"

project/forms.py
from django import forms
from .models import Project, ProjectTeam, User, UserTask,Task # Import your models

class ProjectCreationForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        widgets = {
            # 'status': forms.Select(choices=Status.objects.all()),
            'startDate': forms.DateInput(attrs={'type': 'date'})
        }

# forms.py
from django import forms
from .models import ProjectTeam, User

class ProjectTeamCreationForm(forms.ModelForm):
    class Meta:
        model = ProjectTeam
        fields = ['project', 'users']

    def __init__(self, *args, **kwargs):
        project_id = kwargs.pop('project_id', None)
        selected_users = kwargs.pop('selected_users', [])
        super().__init__(*args, **kwargs)
        if project_id:
            existing_users = ProjectTeam.objects.filter(project_id=project_id).values_list('users', flat=True)
            users_queryset = User.objects.exclude(id__in=existing_users).exclude(id__in=selected_users)
            self.fields['users'].queryset = users_queryset



from django import forms
from .models import ProjectModule



class ProjectModuleCreationForm(forms.ModelForm):
    class Meta:
        model = ProjectModule
        fields = ['project', 'module_Name', 'status', 'description', 'estimated_Minutes',  'start_Date', 'total_Util_Minutes']
      
        statusChoices = [
            ('New', 'New'),
            ('Open', 'Open'),
            ('In progress', 'In progress'),
            ('Completed', 'Completed'),
            ('On Hold', 'On Hold'),  # Add 'On Hold' to the choices
            ('Canceled', 'Canceled'),
            ('Active', 'Active'),
            ('Priority', 'Priority'),
        ]
        widgets = {
            'status': forms.Select(choices=statusChoices),
            'start_Date': forms.DateInput(attrs={'type': 'date'})
        }

class TaskAsignmentForm(forms.ModelForm):
    class Meta:
        model = UserTask
        fields = "__all__"

class TaskCreationForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
    

templates/project/create_task.html
{% extends "../base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<style>
    .bg-black {
        background-color: #000000;
    }
    
    .text-white {
        color: #ffffff;
    }

    #formContent {
        -webkit-border-radius: 10px 10px 10px 10px;
        border-radius: 10px 10px 10px 10px;
        background: #fff;
        padding: 30px;
        width: 90%;
        max-width: 450px;
        position: relative;
        padding: 20px;
        -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
        box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
        text-align: center;
        {% comment %} margin-left: 25px;  {% endcomment %}
        margin: auto; /* Center the form */
      }
    
    .form-group input[type="text"],
    .form-group input[type="password"],
    .form-group input[type="date"],
    .form-group select,
    .form-group textarea {
        background-color: #ffffff;
        border-color: #d6d6d6;
        color: #ffffff;
        border-radius: 8px;
        padding: 8px;
        width: 100%;
        margin: auto;
        
    }
    
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        color: #ffffff;
        border-radius: 5px;
        padding: 10px;
        width: 36%;
        margin: auto; /* Center the form */
    }
    .custom-width {
        width: 61%; /* Adjust the width as needed */
    }
    .custom-mar {
        margin-left: 0px; /* Adjust the side as needed */
    }
    
</style>
<body>
    <br>

    {% comment %} <div class="container wrapper  navbar-expand-lg px-3 py-0 mx-4 shadow border-radius-xl custom-width"> {% endcomment %}
        <br>
        <div class="row custom-mar "> 
            <div class=" row col-md-4 px-3 py-0 mx-4 shadow border-radius-xl card text-left bg-glass   "  >
               
               <br>
               <br> <p class="my-0 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 75%) ">
                Create your Task here..!!
                </p>
{% comment %} <form method="post">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="Submit" />
  </form> {% endcomment %}
  <form method="post"  >
    
    <br>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_project" class="text-white"></label>
        {{ form.project|as_crispy_field }}
    
        <label for="id_module" class="text-white"></label>
        {{ form.module|as_crispy_field }}
        
        <label for="id_title" class="text-white"></label>
        {{ form.title|as_crispy_field }}

        <label for="id_priority" class="text-white"></label>
        {{ form.priority|as_crispy_field }}
        
        {% comment %} <label for="id_created_by" class="text-white"></label>
        {{ form.created_by|as_crispy_field }} {% endcomment %}

        <label for="id_descriptione" class="text-white"></label>
        {{ form.description|as_crispy_field }}

        <label for="id_taskstatus" class="text-white"></label>
        {{ form.taskstatus|as_crispy_field }}

        <label for="id_estimated_Minutes" class="text-white"></label>
        {{ form.estimated_Minutes|as_crispy_field }}

        <label for="id_total_util_minutes" class="text-white"></label>
        {{ form.total_util_minutes|as_crispy_field }}

    </div>
    <br>
    <input type="submit" class="btn btn-primary btn-block" value="Submit" style="width: 98%;">
    <br>
    <br>

</form>
  <br>
</div>
    <div class="row col-md-1 bg-glass  shadow border-radius-xl custom-width">
        <div class="container px-1 py-1 px-md-5 text-center text-lg-start my-5">
            <div class="row gx-lg-2 align-items-center mb-51 justify-content-center">
                <a style="z-index: 10">
                    <h1 class="my-0 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
                    More than just time tracking <br />
                    <span style="color: hsl(218, 81%, 75%)">offers the complete solution for business success.</span>
                    </h1>
                    <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
                    "The key is not to prioritize what's on your schedule, 
                        <br>
                    but to schedule your priorities".
                    </p>
                </a>
                <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
                    <img class="object-cover object-center rounded" alt="hero" src="https://source.unsplash.com/610x1010/?coding">
                </div>
            </div>
        </div>      
    </div>
</div>



</body>
</html>

{% endblock content %}

templates/project/detail.html
{% extends "../base.html" %}
{% block content %}
<div class="row px-md-3 card-body p-1 bg-glass shadow border-radius-xl my-5 mb-3 mx-3">
    <div class="container px-1 py-1 px-md-5 text-center text-lg-start my-5">
        <div class="row">
            <div class="col-md-6">
                <a style="z-index: 100">
                    <h1 class="my-0 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
                        Project title ..!!
                        <br>
                        <span style="color: hsl(218, 81%, 75%)" class="mb-4">{{ project.title }} </span>
                    </h1>
                    
                    <p class="mb-2 opacity-70" style="color: hsl(218, 81%, 85%)">
                       
                        </a>
                    </p>
                    <p class="mb-2 opacity-70" style="color: hsl(218, 81%, 85%)">
                       Technology :   <a class="mb-2 text-secondary"> {{ project.technology }}  
                        </a>
                    </p>
                    <p class="mb-2 opacity-70" style="color: hsl(218, 81%, 85%)">
                    Estimated Time Duration :  <a class="mb-2 text-secondary"> {{ project.estimated_hours }} Hours
                    </a>
                    <p class="mb-2  opacity-70" style="color: hsl(218, 81%, 85%)">
                        Durations : 
                        <a class="mb-2 text-secondary"> {{  project.startDate }} to {{ project.endDate }}
                        </a>
                        </p>
                        <p class="mb-2 opacity-70" style="color: hsl(218, 81%, 85%)">
                            Team members:
                            <a class="mb-2 text-secondary">
                               
                            {% for team_member in team_members %}
                                {% for user in team_member.users.all %}
                                    <li>{{ user }}</li>
                                {% endfor %}
                            {% endfor %}
                            </a>
                            {% comment %} <a href="{% url 'module_create' project.id %}"class="btn btn-dark text-secondary font-weight-bold text-xs mt-0 mb-0 btn btn-outline-gray">CREATE TASK</a> {% endcomment %}



                    <p class="mb-2 opacity-70" style="color: hsl(218, 81%, 85%)">
                        Description : <a class="mb-2 text-secondary"> {{ project.description }}
                    </a>
                </p>
            
            </div>
            <div class="col-md-4">
                <div class="row gx-lg-10 align-items-center mb-51 justify-content-center">
                    <div class="lg:max-w-lg lg:w-full md:w-1/1 w-5/6">
                        <img class="object-cover object-center rounded" alt="hero" src="https://source.unsplash.com/500x480/?programming">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/project/module_create.html
{% extends "../base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<style>
    .bg-black {
        background-color: #000000;
    }
    
    .text-white {
        color: #ffffff;
    }

    #formContent {
        -webkit-border-radius: 10px 10px 10px 10px;
        border-radius: 10px 10px 10px 10px;
        background: #fff;
        padding: 30px;
        width: 90%;
        max-width: 450px;
        position: relative;
        padding: 20px;
        -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
        box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
        text-align: center;
        {% comment %} margin-left: 25px;  {% endcomment %}
        margin: auto; /* Center the form */
      }
    
    .form-group input[type="text"],
    .form-group input[type="password"],
    .form-group input[type="date"],
    .form-group select,
    .form-group textarea {
        background-color: #ffffff;
        border-color: #d6d6d6;
        color: #ffffff;
        border-radius: 8px;
        padding: 8px;
        width: 100%;
        margin: auto;
        
    }
    
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        color: #ffffff;
        border-radius: 5px;
        padding: 10px;
        width: 36%;
        margin: auto; /* Center the form */
    }
    .custom-width {
        width: 61%; /* Adjust the width as needed */
    }
    .custom-mar {
        margin-left: 0px; /* Adjust the side as needed */
    }
    
</style>
<body>
    <br>

    {% comment %} <div class="container wrapper  navbar-expand-lg px-3 py-0 mx-4 shadow border-radius-xl custom-width"> {% endcomment %}
        <br>
        <div class="row custom-mar "> 
            <div class=" row col-md-4 px-3 py-0 mx-4 shadow border-radius-xl card text-left bg-glass   "  >
               <br>
               <br> <p class="my-0 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 75%) ">
                Create your Module here..!!
                </p>
                <form method="post"  >
                    {% csrf_token %}
                    <div class="form-group ">
                        <label for="id_project" class="text-white"></label>
                        {{ form.project|as_crispy_field }}
                    
                        <label for="id_module_Name" class="text-white"></label>
                        {{ form.module_Name|as_crispy_field }}

                      <label for="id_description" class="text-white"></label>
                        {{ form.description|as_crispy_field }}

                        <label for="id_status" class="text-white"> </label>
                        {{ form.status|as_crispy_field }}

                        <label for="id_estimated_Minutes" class="text-white"> </label>
                        {{ form.estimated_Minutes|as_crispy_field }}
                    
                        <label for="id_start_Date" class="text-white"> </label>
                        {{ form.start_Date|as_crispy_field }}
                   
                        <label for="id_total_Util_Minutes" class="text-white"> </label>
                        {{ form.total_Util_Minutes|as_crispy_field }}
                    </div>
                    
                    <br>
                    <input type="submit" class="btn btn-primary btn-block" value="Create" style="width: 98%;">
                    <br>
                    <br>
            
                </form>
            <br>
            </div>
                <div class="row col-md-1 bg-glass  shadow border-radius-xl custom-width">
                    <div class="container px-1 py-1 px-md-5 text-center text-lg-start my-5">
                        <div class="row gx-lg-2 align-items-center mb-51 justify-content-center">
                            <a style="z-index: 10">
                                <h1 class="my-0 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
                                More than just time tracking <br />
                                <span style="color: hsl(218, 81%, 75%)">offers the complete solution for business success.</span>
                                </h1>
                                <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
                                "The key is not to prioritize what's on your schedule, 
                                    <br>
                                but to schedule your priorities".
                                </p>
                            </a>
                            <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
                                <img class="object-cover object-center rounded" alt="hero" src="https://source.unsplash.com/600x720/?coding">
                            </div>
                        </div>
                    </div>      
                </div>
            </div>
            
       

</body>
</html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        // Initialize Select2 dropdown
        $('#team-members').select2({
            placeholder: 'Select team members',
            // Add your configuration options here
        });
    });
</script>
{% endblock content %}


{% comment %} {% extends "../base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block content %}


<div class="container">
   <div class="row">
       <div class="col-md-6">
           <H2>UPDATE</H2>

           <form method="POST">
               {% csrf_token %}
               {{form|crispy}}
               <button type="submit" class="btn btn-primary">UPDATE</button>
           </form>
       </div>
   </div>


{% endblock content %} {% endcomment %}

templates/project/module_update.html
{% extends "../base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<style>
    .bg-black {
        background-color: #000000;
    }
    
    .text-white {
        color: #ffffff;
    }

    #formContent {
        -webkit-border-radius: 10px 10px 10px 10px;
        border-radius: 10px 10px 10px 10px;
        background: #fff;
        padding: 30px;
        width: 90%;
        max-width: 450px;
        position: relative;
        padding: 20px;
        -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
        box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
        text-align: center;
        {% comment %} margin-left: 25px;  {% endcomment %}
        margin: auto; /* Center the form */
      }
    
    .form-group input[type="text"],
    .form-group input[type="password"],
    .form-group input[type="date"],
    .form-group select,
    .form-group textarea {
        background-color: #ffffff;
        border-color: #d6d6d6;
        color: #ffffff;
        border-radius: 8px;
        padding: 8px;
        width: 100%;
        margin: auto;
        
    }
    
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        color: #ffffff;
        border-radius: 5px;
        padding: 10px;
        width: 36%;
        margin: auto; /* Center the form */
    }
    .custom-width {
        width: 61%; /* Adjust the width as needed */
    }
    .custom-mar {
        margin-left: 0px; /* Adjust the side as needed */
    }
    
</style>
<body>
    <br>

    {% comment %} <div class="container wrapper  navbar-expand-lg px-3 py-0 mx-4 shadow border-radius-xl custom-width"> {% endcomment %}
        <br>
        <div class="row custom-mar "> 
            <div class=" row col-md-4 px-3 py-0 mx-4 shadow border-radius-xl card text-left bg-glass   "  >
               <br>
               <br> <p class="my-0 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 75%) ">
                Update your Module here..!!
                </p>
                <form method="post"  >
                    {% csrf_token %}
                    <div class="form-group ">
                        <label for="id_project" class="text-white"></label>
                        {{ form.project|as_crispy_field }}
                    
                        <label for="id_module_Name" class="text-white"></label>
                        {{ form.module_Name|as_crispy_field }}

                      <label for="id_description" class="text-white"></label>
                        {{ form.description|as_crispy_field }}

                        <label for="id_status" class="text-white"> </label>
                        {{ form.status|as_crispy_field }}

                        <label for="id_estimated_Minutes" class="text-white"> </label>
                        {{ form.estimated_Minutes|as_crispy_field }}
                    
                        <label for="id_start_Date" class="text-white"> </label>
                        {{ form.start_Date|as_crispy_field }}
                   
                        <label for="id_total_Util_Minutes" class="text-white"> </label>
                        {{ form.total_Util_Minutes|as_crispy_field }}
                    </div>
                    
                    <br>
                    <input type="submit" class="btn btn-primary btn-block" value="Update" style="width: 98%;">
                    <br>
                    <br>
            
                </form>
            <br>
            </div>
                <div class="row col-md-1 bg-glass  shadow border-radius-xl custom-width">
                    <div class="container px-1 py-1 px-md-5 text-center text-lg-start my-5">
                        <div class="row gx-lg-2 align-items-center mb-51 justify-content-center">
                            <a style="z-index: 10">
                                <h1 class="my-0 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
                                More than just time tracking <br />
                                <span style="color: hsl(218, 81%, 75%)">offers the complete solution for business success.</span>
                                </h1>
                                <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
                                "The key is not to prioritize what's on your schedule, 
                                    <br>
                                but to schedule your priorities".
                                </p>
                            </a>
                            <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
                                <img class="object-cover object-center rounded" alt="hero" src="https://source.unsplash.com/600x720/?coding">
                            </div>
                        </div>
                    </div>      
                </div>
            </div>
            
       

</body>
</html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        // Initialize Select2 dropdown
        $('#team-members').select2({
            placeholder: 'Select team members',
            // Add your configuration options here
        });
    });
</script>
{% endblock content %}


{% comment %} {% extends "../base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block content %}


<div class="container">
   <div class="row">
       <div class="col-md-6">
           <H2>UPDATE</H2>

           <form method="POST">
               {% csrf_token %}
               {{form|crispy}}
               <button type="submit" class="btn btn-primary">UPDATE</button>
           </form>
       </div>
   </div>


{% endblock content %} {% endcomment %}